export { default as Home } from './home'
export { default as Layout } from './layout'
export { default as Login } from './login'
export { default as NotFound } from './not-found'
export { default as RegisterPage } from './register'